### ISSUE TITLE
Update API with Authencation via command line - data to be updated.

### ISSUE THREAD

**Issue by padmaraj85** [TykTechnologies/tyk-docs-hugo#1164]
Hi,

I was following the instructions on the [link](https://tyk.io/docs/try-out-tyk/tutorials/create-api/#protect-your-api) to Protect API (SaaS version).

I tried updating the filed in config as given in the link and found it to be not working as expected. 
Below is the reference from Tyk documentation.
<img width="1016" alt="TykDoc" src="https://user-images.githubusercontent.com/38547140/79541113-d8a2a980-80bb-11ea-9ff3-e87a990aea16.png">

Later I found it to be working as expected by updating another field similar to the one given in the documentation. Please refer to the highlighted one in below pic.

<img width="394" alt="Screenshot 2020-04-16 at 7 20 00 PM" src="https://user-images.githubusercontent.com/38547140/79541281-20293580-80bc-11ea-909a-b45e8ce7fc2a.png">

Please help to cross-check and update the doc.

**Comment by marksou** [comment]
Hi @padmaraj85 This is due to `auth.auth_header_name` being deprecated from v2.9.2, with `auth_configs.auth_header_name` replacing it. See the bottom of [here](https://tyk.io/docs/tyk-apis/tyk-gateway-api/api-definition-objects/authentication/) I'll add a note on that page. It may be worth checking with someone whether we intend removing the `auth` value at some point.
