### ISSUE TITLE
Create videos for "Best practice for configuring Tyk Hybrid and On-prem"

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#287]
From customer insights meeting: A topic came up around customers not knowing the optimum way of configuring their infrastructure for Tyk Hybrid/On-prem - we suggested doing some "best practice configuring tyk" type videos.

**Comment by marksou** [comment]
Have we got info on the customer's setup (no of APIs, request traffic), etc?

**Comment by james-tyk** [comment]
I think we should run with 3 validated approaches:

1.  Minimum viable proposition - single node, no HA.
2.  Scaled for peaks of 5,000 RPS and HA (3 nodes)
3.  MDCB in two DCs/Regions

Open to having this corrected, but seems like then users can see progression from POC through to Enterprise and extrapolate something specific to their needs from it.

**Comment by james-tyk** [comment]
(and if there are to be videos, starting point should be text and still images, then when happy with that, add video ontop)

**Comment by nickReyn** [comment]
Well I think the idea behind it was that one of the CE's would video themselves setting it up and speaking through it, so wouldn't need much post production type stuff. Let me know if I have mis-understood @asoorm, as was your idea.

**Comment by james-tyk** [comment]
That would be great for the video, my contention is more that there are many ways to setup Tyk - we need to show some exemplars, otherwise anyone finding this video will think that we only do it one way... so we need to show options and context, then video for that particular example.  I'm always worried that small users will be put off by the Enterprise scale requirements, and conversely, Enterprise customers will only see the MVP scale stuff and pass us over as too small.
