### ISSUE TITLE
The Docker Quickstart guide references a non-existent repo

### ISSUE THREAD

**Issue by dijitali** [TykTechnologies/tyk-docs-hugo#588]
The guide references a docker compose file here:
https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/#step-2-get-the-quick-start-compose-files

But this repo is not available:
https://github.com/TykTechnologies/tyk_quickstart.git

It would be great to have a basic working docker setup so we can work locally when developing Tyk configuration and customisations.

**Comment by dijitali** [comment]
Actually looks like it might be here now:
https://github.com/TykTechnologies/tyk-pro-docker-demo

**Comment by marksou** [comment]
@dijitali We removed the Docker Quickstart docs and repo. The Pro Docker demo is the one to go to now.

**Comment by dijitali** [comment]
@marksou - awesome thanks, that repo is working well.  I think there's just an out-of-date link to the old repo here:
https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/docker-quickstart.md#step-2-get-the-docker-demo-compose-files

**Comment by marksou** [comment]
@dijitali This page is hidden from the Docs menu, but still gets hit by searches, and in the code build. Probably the best thing we can do is to remove it completely to avoid confusion.

**Comment by dijitali** [comment]
@marksou - ah that makes sense. I probably came across it via Google.  

The docker setup is really handy for us; I'd suggest just linking to this new repo rather than removing the help entirely but whatever makes sense for you.

**Comment by festinuz** [comment]
Please update https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/docker-quickstart/ as it is first hit on google when searching for "tyk docker quickstart" and the current situation is confusing.

I'm coming to this issue because i  wanted to create a new one about missing repository and found this one. I assume there are more people like me that google this and are therefore misled by outdated docs.
